services:
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      votingnetwork:
        ipv4_address: ${REDIS_IP}
  votes:
    build: 
      context: ./votes/
      target: prod
    depends_on:
      - redis
    ports:
      - "3000:3000"
    networks:
      - votingnetwork
networks:
  votingnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
