apiVersion: v1
kind: Service
metadata:
  labels:
    application: redis
  name: redis
spec:
  selector:
    application: redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: 172.28.5.20
  type: ClusterIP  