apiVersion: v1
kind: Service
metadata:
  labels:
    application: votes
  name: votes
spec:
  selector:
    application: votes
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: 172.28.0.2
  type: ClusterIP
